channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch-cuda=11.6
  - pytorch
  - torchvision
  - pip:
      - -e . # install package itself
      - pytorch-lightning==1.9.3
      - tqdm==4.64.1
      - albumentations[imgaug]==1.3.0
      - pandas==1.5.3
      - wandb==0.13.10
      - black==23.1.0 # code format
      - opencv-python==4.7.0.72
